### ISSUE TITLE
gethue/hue:latest - Map-Reduce job in workflow is not using the job properties while submitting Oozie workflow

### ISSUE THREAD

**Issue by connected-yzhao** [gethue/hue#8]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
The map-reduce action properties are not rendered while submitting the Oozie workflow

Steps to reproduce it?
Create a workflow with one map-reduce job and configure the property within the action and submit the workflow.
![image (18)](https://user-images.githubusercontent.com/52470166/107243322-e3d41680-69fa-11eb-9813-20ac7b85a2e8.png)
The workflow will fail and the workflow.xml shows the job properties are not rendered
![image (20)](https://user-images.githubusercontent.com/52470166/107245359-0ebf6a00-69fd-11eb-90a0-5d23513e37a5.png)
![image (19)](https://user-images.githubusercontent.com/52470166/107245367-1252f100-69fd-11eb-9a1e-095a07f7c318.png)
But setting the properties in the global setting will render successfully.
![image (17)](https://user-images.githubusercontent.com/52470166/107245470-31518300-69fd-11eb-8eb9-ffbff65702dc.png)
![image (21)](https://user-images.githubusercontent.com/52470166/107245736-7d042c80-69fd-11eb-94f5-909513b29591.png)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
We are using the latest gethue/hue image and the Ooizie cluster version is 4.3.1, and the Big Data Europe Hadoop cluster version [3.1.1](https://github.com/big-data-europe/docker-hadoop/tree/3.1.1)

**Comment by romainr** [comment]
Please upgrade to a more recent Hue, at least 4.8
